title: ResultWizard
description: Documentation for the ResultWizard Python library.
theme: just-the-docs
include: ["pages"]
logo: "https://github.com/resultwizard/ResultWizard/assets/37160523/e3ce32b9-2e41-4ddc-88e3-c1adadd305e9"

url: https://resultwizard.github.io/ResultWizard/

aux_links:
  GitHub: https://github.com/resultwizard/ResultWizard
  PyPI: https://pypi.org/project/resultwizard/

enable_copy_code_button: true

color_scheme: resultwizard-colors
callouts:
  warning:
    title: Warning
    color: resultwizard-warning-purple
    opacity: 0.1
