name: Documentation

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "docs/**"

jobs:
  # Just check that the build works and doesn't throw any errors
  # The actual build and deployment is done on the main branch
  # with another GitHub Actions workflow.
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
          working-directory: '${{ github.workspace }}/docs'

      - name: Build with Jekyll
        run: bundle exec jekyll build
